[package]
name = "stellar-core"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_stellar_core"
crate-type = ["staticlib"]

[dependencies]
cxx = "1.0"
base64 = "0.13.0"
stellar-contract-env-host = { git = "https://github.com/stellar/rs-stellar-contract-env", rev = "d0a4b13881fa95a7174390f685b18f9941c9094a", features = [
    "vm",
] }
