[package]
name = "stellar-core"
version = "0.1.0"
edition = "2021"
rust-version = "1.74"
publish = false

[lib]
name = "rust_stellar_core"
crate-type = ["staticlib"]

[dependencies]
log = "=0.4.19"
tracy-client = { version = "=0.16.4", features = ["enable"], default-features = false, optional = true}
cxx = "=1.0.97"
base64 = "=0.13.1"
rustc-simple-version = "=0.1.0"
# NB: this must match the same rand version used by soroban (but the tooling
# will complain if it does not match)
rand = "=0.8.5"

petgraph = "=0.6.4"
toml = "=0.7.8"
itertools = "=0.11.0"

# This copy of the soroban host is always enabled, and should always point to a
# version that supports stellar-core's Config::CURRENT_LEDGER_PROTOCOL_VERSION.
# When upgrading from protocol N to N+1, this copy will therefore have its
# version advance first (to enable support for N+1) even before the network has
# voted to upgrade to it. In order to avoid divergence during such an upgrade,
# we will simultaneously enable the `prev` copy of soroban (below), continuing
# to point to the previous already-released soroban that only supported protocol
# N.

[dependencies.soroban-env-host-curr]
version = "=21.1.0"
git = "https://github.com/stellar/rs-soroban-env"
package = "soroban-env-host"
rev = "8d76e4037417b80dc25c979cc44b8e1281e8ad84"

# When transitioning from protocol N to N+1, the `curr` copy
# (above) will bump its version to one that supports protocol N+1, and we will
# point this `prev` copies version and git rev to the
# last soroban released to the network that speaks protocol N. When we deploy
# this to a network running protocol N it will run on `prev` until the upgrade,
# then switch from `prev` to `curr` at the upgrade.

[dependencies.soroban-env-host-prev]
optional = true
version = "=20.3.0"
git = "https://github.com/stellar/rs-soroban-env"
package = "soroban-env-host"
rev = "93120b6b32cd910fcc224cbf6aec1333f771a8bc"

[dependencies.soroban-test-wasms]
version = "=21.1.0"
git = "https://github.com/stellar/rs-soroban-env"
rev = "8d76e4037417b80dc25c979cc44b8e1281e8ad84"

[dependencies.soroban-synth-wasm]
version = "=21.1.0"
git = "https://github.com/stellar/rs-soroban-env"
rev = "8d76e4037417b80dc25c979cc44b8e1281e8ad84"

[dependencies.cargo-lock]
version = "=9.0.0"
git = "https://github.com/rustsec/rustsec"
rev = "a5c69fc6e4b6068b43d7143f3a2f68c3f3de37d8"
features = ["dependency-tree"]

# This feature definition is implied by the optional=true line in the dep, but
# writing it out in full here cross-checks that nobody _removed_ that line.
[features]
tracy = ["dep:tracy-client", "soroban-env-host-curr/tracy"]
core-vnext = ["soroban-env-host-curr/next"]
